import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';

const root = resolve(import.meta.dirname, '..');
const runtimeServicePath = resolve(root, 'src/services/acceleration-runtime.service.ts');
const runtimeStatePath = resolve(root, 'src/services/acceleration-runtime-state.service.ts');
const runtimeAdminControlPath = resolve(root, 'src/services/runtime-admin-control.service.ts');
const runtimeAdminReconcileControlPath = resolve(root, 'src/services/runtime-admin-reconcile-control.service.ts');
const runtimeAdminRoutesPath = resolve(root, 'src/routes/runtime-admin.routes.ts');
const runtimeAdminEndpointTypesPath = resolve(root, 'src/routes/runtime-admin-endpoint-types.ts');
const runtimeAdminEndpointHandlersPath = resolve(root, 'src/routes/runtime-admin-endpoint-handlers.ts');
const runtimeAdminTransportPath = resolve(root, 'src/routes/runtime-admin-transport.ts');
const runtimeAdminReconcileExecutorPath = resolve(root, 'src/routes/runtime-admin-reconcile-executor.ts');
const runtimeMiddlewarePath = resolve(root, 'src/middleware/acceleration-runtime-gate.middleware.ts');
const appPath = resolve(root, 'src/app.ts');
const runtimeService = readFileSync(runtimeServicePath, 'utf8');
const runtimeState = readFileSync(runtimeStatePath, 'utf8');
const runtimeAdminControl = readFileSync(runtimeAdminControlPath, 'utf8');
const runtimeAdminReconcileControl = readFileSync(runtimeAdminReconcileControlPath, 'utf8');
const runtimeAdminRoutes = readFileSync(runtimeAdminRoutesPath, 'utf8');
const runtimeAdminEndpointTypes = readFileSync(runtimeAdminEndpointTypesPath, 'utf8');
const runtimeAdminEndpointHandlers = readFileSync(runtimeAdminEndpointHandlersPath, 'utf8');
const runtimeAdminTransport = readFileSync(runtimeAdminTransportPath, 'utf8');
const runtimeAdminReconcileExecutor = readFileSync(runtimeAdminReconcileExecutorPath, 'utf8');
const runtimeMiddleware = readFileSync(runtimeMiddlewarePath, 'utf8');
const appSource = readFileSync(appPath, 'utf8');

test('acceleration runtime state lives in a dedicated kernel-state module', () => {
  assert.equal(existsSync(runtimeStatePath), true, 'acceleration-runtime-state.service.ts must exist');
  assert.match(runtimeState, /export type AccelerationRuntimePhase/);
  assert.match(runtimeState, /export type AccelerationRuntimeState/);
  assert.match(runtimeState, /export type AccelerationRuntimeApiRequestLease/);
  assert.match(runtimeState, /export function getAccelerationRuntimeSnapshot/);
  assert.match(runtimeState, /export function setAccelerationRuntimePhase/);
  assert.match(runtimeState, /export function setAccelerationRuntimeBlocking/);
  assert.match(runtimeState, /export function acquireAccelerationRuntimeApiRequest/);
  assert.match(runtimeState, /export async function waitForAccelerationApiIdle/);
  assert.doesNotMatch(runtimeState, /export const accelerationRuntime/);
  assert.doesNotMatch(runtimeState, /import type \{ Request, RequestHandler \} from 'express'/);
  assert.doesNotMatch(runtimeState, /sendErrorEnvelope/);
  assert.doesNotMatch(runtimeState, /createAccelerationRuntimeMiddleware/);
  assert.doesNotMatch(runtimeState, /function isTrackedAccelerationApiRequest/);
});

test('acceleration runtime service re-exports snapshot access but does not own middleware state logic', () => {
  assert.match(runtimeService, /from '\.\/acceleration-runtime-state\.service'/);
  assert.match(runtimeService, /getAccelerationRuntimeSnapshot/);
  assert.doesNotMatch(runtimeService, /\baccelerationRuntime,/);
  assert.doesNotMatch(runtimeService, /import type \{ Request, RequestHandler \} from 'express'/);
  assert.doesNotMatch(runtimeService, /sendErrorEnvelope/);
  assert.doesNotMatch(runtimeService, /activeApiRequests \+= 1/);
  assert.doesNotMatch(runtimeService, /activeApiRequests = Math\.max/);
  assert.doesNotMatch(runtimeService, /setAccelerationRuntimeBlocking\(true\)/);
  assert.doesNotMatch(runtimeService, /setAccelerationRuntimeBlocking\(false\)/);
  assert.doesNotMatch(runtimeService, /waitForAccelerationApiIdle\(\)/);
  assert.doesNotMatch(runtimeService, /function isTrackedAccelerationApiRequest/);
  assert.doesNotMatch(runtimeService, /createAccelerationRuntimeMiddleware/);
});

test('acceleration runtime state owns leases while middleware owns HTTP request gating', () => {
  assert.match(runtimeState, /let accelerationRuntimeSnapshot: AccelerationRuntimeState/);
  assert.match(runtimeState, /Object\.freeze\(\{/);
  assert.match(runtimeState, /function publishAccelerationRuntimeSnapshot/);
  assert.match(runtimeState, /export function setAccelerationRuntimeBlocking\(blocking: boolean\)/);
  assert.match(runtimeState, /export function acquireAccelerationRuntimeApiRequest\(\): AccelerationRuntimeApiRequestAcquireResult/);
  assert.match(runtimeState, /status: 'blocked'/);
  assert.match(runtimeState, /status: 'acquired'/);
  assert.match(runtimeState, /publishAccelerationRuntimeSnapshot\(\{\s*activeApiRequests: snapshot\.activeApiRequests \+ 1,/);
  assert.match(runtimeState, /activeApiRequests: Math\.max\(0, getAccelerationRuntimeSnapshot\(\)\.activeApiRequests - 1\)/);
  assert.match(runtimeState, /while \(getAccelerationRuntimeSnapshot\(\)\.activeApiRequests > 0/);
  assert.doesNotMatch(runtimeState, /accelerationRuntime\.(phase|message|stale|lastCompiledSignature|lastError|blocking|activeApiRequests)\s*=/);
  assert.doesNotMatch(runtimeState, /activeApiRequests \+= 1/);
  assert.equal(existsSync(runtimeMiddlewarePath), true, 'acceleration-runtime-gate.middleware.ts must exist');
  assert.match(runtimeMiddleware, /import type \{ Request, RequestHandler, Response \} from 'express'/);
  assert.match(runtimeMiddleware, /acquireAccelerationRuntimeApiRequest/);
  assert.match(runtimeMiddleware, /sendErrorEnvelope/);
  assert.match(runtimeMiddleware, /function isTrackedAccelerationApiRequest/);
  assert.match(runtimeMiddleware, /export function createAccelerationRuntimeMiddleware\(\): RequestHandler/);
  assert.match(runtimeMiddleware, /requestLease\.status === 'blocked'/);
  assert.match(runtimeMiddleware, /sendAccelerationRuntimeWarming\(req, res, requestLease\.snapshot\)/);
  assert.match(runtimeMiddleware, /res\.setHeader\('Retry-After', '1'\)/);
  assert.match(runtimeMiddleware, /res\.on\('finish', requestLease\.release\)/);
  assert.match(runtimeMiddleware, /res\.on\('close', requestLease\.release\)/);
  assert.match(appSource, /from '\.\/middleware\/acceleration-runtime-gate\.middleware'/);
  assert.match(appSource, /app\.use\(createAccelerationRuntimeMiddleware\(\)\)/);
});

test('runtime admin routes consume acceleration snapshots explicitly', () => {
  assert.match(runtimeAdminEndpointTypes, /getAccelerationRuntimeSnapshot: \(\) => AccelerationRuntimeState/);
  assert.match(runtimeAdminEndpointHandlers, /getRuntimeAdminHealth/);
  assert.match(runtimeAdminEndpointHandlers, /getRuntimeAdminDiagnostics/);
  assert.match(runtimeAdminEndpointHandlers, /getRuntimeOpenApiDocument/);
  assert.match(runtimeAdminEndpointHandlers, /getPublicApiIndex/);
  assert.match(runtimeAdminEndpointHandlers, /sendRuntimeAdminJson/);
  assert.match(runtimeAdminEndpointHandlers, /sendRuntimeAdminOpenApi/);
  assert.match(runtimeAdminEndpointHandlers, /sendRuntimeAdminReconcile/);
  assert.match(runtimeAdminEndpointHandlers, /getRuntimeAdminHealth\(options\.getAccelerationRuntimeSnapshot\(\)\)/);
  assert.match(runtimeAdminEndpointHandlers, /getRuntimeAdminDiagnostics\(options\.getAccelerationRuntimeSnapshot\(\)\)/);
  assert.match(runtimeAdminRoutes, /createRuntimeAdminIndexEndpointHandlers\(options\)/);
  assert.match(runtimeAdminRoutes, /createRuntimeAdminControlEndpointHandlers\(label, options\)/);
  assert.doesNotMatch(runtimeAdminRoutes, /function serializeAccelerationRuntime/);
  assert.doesNotMatch(runtimeAdminRoutes, /serializeAccelerationRuntime/);
  assert.doesNotMatch(runtimeAdminRoutes, /getRuntimeAdminHealth/);
  assert.doesNotMatch(runtimeAdminRoutes, /getRuntimeAdminDiagnostics/);
  assert.doesNotMatch(runtimeAdminRoutes, /getRuntimeOpenApiDocument/);
  assert.doesNotMatch(runtimeAdminRoutes, /getPublicApiIndex/);
  assert.doesNotMatch(runtimeAdminRoutes, /sendRuntimeAdminJson/);
  assert.doesNotMatch(runtimeAdminRoutes, /sendRuntimeAdminOpenApi/);
  assert.doesNotMatch(runtimeAdminRoutes, /setPublicCacheHeaders/);
  assert.doesNotMatch(runtimeAdminRoutes, /sendErrorEnvelope/);
  assert.doesNotMatch(runtimeAdminRoutes, /logger/);
  assert.doesNotMatch(runtimeAdminRoutes, /res\.status\(202\)/);
  assert.doesNotMatch(runtimeAdminRoutes, /res\.json\(\{/);
  assert.doesNotMatch(runtimeAdminRoutes, /fs\.existsSync/);
  assert.doesNotMatch(runtimeAdminRoutes, /PUBLISH_OUTPUT_DIR/);
  assert.doesNotMatch(runtimeAdminRoutes, /\baccelerationRuntime\b/);
  assert.match(runtimeAdminControl, /export function serializeAccelerationRuntime/);
  assert.match(runtimeAdminControl, /export function getRuntimeAdminHealth/);
  assert.match(runtimeAdminControl, /serializeAccelerationRuntime\(snapshot\)/);
  assert.match(runtimeAdminControl, /export function getRuntimeAdminDiagnostics/);
  assert.match(runtimeAdminControl, /export function getRuntimeOpenApiDocument/);
  assert.match(runtimeAdminControl, /export function getPublicApiIndex/);
  assert.match(runtimeAdminControl, /fs\.existsSync\(PUBLISH_OUTPUT_DIR\)/);
  assert.match(runtimeAdminControl, /Object\.freeze\(\{/);
  assert.doesNotMatch(runtimeAdminRoutes, /getAccelerationReconcileConflict/);
  assert.doesNotMatch(runtimeAdminRoutes, /getAccelerationManagerUnavailableError/);
  assert.doesNotMatch(runtimeAdminRoutes, /getAccelerationReconcileAccepted/);
  assert.doesNotMatch(runtimeAdminRoutes, /getAccelerationReconcileFailureTransition/);
  assert.doesNotMatch(runtimeAdminRoutes, /ACCELERATION_MANAGER_NOT_READY/);
  assert.doesNotMatch(runtimeAdminRoutes, /ACCELERATION_RECONCILE_IN_PROGRESS/);
  assert.doesNotMatch(runtimeAdminRoutes, /accelerationSnapshot\.phase === 'compiling'/);
  assert.doesNotMatch(runtimeAdminRoutes, /accelerationSnapshot\.phase === 'promoting'/);
  assert.doesNotMatch(runtimeAdminRoutes, /Acceleration reconciliation scheduled\./);
  assert.match(runtimeAdminTransport, /sendErrorEnvelope/);
  assert.match(runtimeAdminTransport, /setPublicCacheHeaders/);
  assert.match(runtimeAdminTransport, /export function sendRuntimeAdminControlError/);
  assert.match(runtimeAdminTransport, /export function createRuntimeAdminTokenMiddleware/);
  assert.match(runtimeAdminTransport, /export function sendRuntimeAdminOpenApi/);
  assert.match(runtimeAdminTransport, /export function sendRuntimeAdminAccepted/);
  assert.match(runtimeAdminReconcileExecutor, /getAccelerationReconcileConflict/);
  assert.match(runtimeAdminReconcileExecutor, /getAccelerationManagerUnavailableError/);
  assert.match(runtimeAdminReconcileExecutor, /getAccelerationReconcileAccepted/);
  assert.match(runtimeAdminReconcileExecutor, /getAccelerationReconcileFailureTransition/);
  assert.match(runtimeAdminReconcileExecutor, /logger\.info/);
  assert.match(runtimeAdminReconcileExecutor, /logger\.error/);
  assert.match(runtimeAdminReconcileExecutor, /reconcileAccelerationRuntime\(manager\)\.catch/);
  assert.match(runtimeAdminReconcileExecutor, /setAccelerationRuntimePhase\(transition\.phase, transition\.message, transition\.extras\)/);
  assert.match(runtimeAdminReconcileControl, /export function getAccelerationManagerUnavailableError/);
  assert.match(runtimeAdminReconcileControl, /export function getAccelerationReconcileConflict/);
  assert.match(runtimeAdminReconcileControl, /export function getAccelerationReconcileAccepted/);
  assert.match(runtimeAdminReconcileControl, /export function getAccelerationReconcileFailureTransition/);
  assert.match(runtimeAdminReconcileControl, /ACCELERATION_MANAGER_NOT_READY/);
  assert.match(runtimeAdminReconcileControl, /ACCELERATION_RECONCILE_IN_PROGRESS/);
  assert.match(runtimeAdminReconcileControl, /snapshot\.phase !== 'compiling'/);
  assert.match(runtimeAdminReconcileControl, /snapshot\.phase !== 'promoting'/);
  assert.match(appSource, /getAccelerationRuntimeSnapshot/);
  assert.match(appSource, /getAccelerationRuntimeSnapshot,/);
  assert.doesNotMatch(appSource, /\baccelerationRuntime,/);
  assert.doesNotMatch(appSource, /accelerationRuntime:/);
});
