import assert from 'node:assert/strict';
import { execFileSync } from 'node:child_process';
import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import test from 'node:test';
import {
  ELYSIUM_COMPILER_CAPABILITY_ABI,
  ELYSIUM_COMPILER_CAPABILITY_SOURCE,
  NATIVE_UI_FALLBACK_POLICY,
  NATIVE_UI_REQUIRED_CAPABILITIES,
  REQUIRED_COMPILER_COMMAND_INVOCATIONS,
  validateElysiumCompilerCapabilityAbi,
} from '../../scripts/elysium-compiler-capability-abi.mjs';

const root = resolve(import.meta.dirname, '..');
const repoRoot = resolve(root, '..');
const clientSource = readFileSync(resolve(root, 'src/compiler-client/elysium-compiler-client.ts'), 'utf8');
const catalogSource = readFileSync(resolve(root, 'src/compiler-client/elysium-compiler-capability-abi.ts'), 'utf8');
const gateSource = readFileSync(resolve(root, 'src/compiler-client/elysium-compiler-capability-gate.ts'), 'utf8');
const scriptCatalogSource = readFileSync(resolve(root, '../scripts/elysium-compiler-capability-abi.mjs'), 'utf8');
const capabilityArtifact = JSON.parse(
  readFileSync(resolve(root, '../tools/elysium-compiler/elysium-compiler-capability-abi.json'), 'utf8'),
);
const ensureSource = readFileSync(resolve(root, '../scripts/ensure-elysium-compiler.mjs'), 'utf8');
const runtimeSource = readFileSync(resolve(root, 'src/services/acceleration-runtime.service.ts'), 'utf8');
const reporterSource = readFileSync(resolve(root, 'src/services/acceleration-runtime-compiler-boundary-reporter.service.ts'), 'utf8');

test('backend capability catalog is generated from the locked compiler schema artifact', () => {
  execFileSync(process.execPath, ['scripts/sync-elysium-compiler-capability-abi.mjs', '--check'], {
    cwd: repoRoot,
    stdio: 'pipe',
  });
  assert.match(catalogSource, /Generated by scripts\/sync-elysium-compiler-capability-abi\.mjs/);
  assert.deepEqual(ELYSIUM_COMPILER_CAPABILITY_ABI.nativeUi, capabilityArtifact.nativeUi);
  assert.deepEqual(ELYSIUM_COMPILER_CAPABILITY_ABI.policy, capabilityArtifact.policy);
  assert.deepEqual(ELYSIUM_COMPILER_CAPABILITY_SOURCE, capabilityArtifact.source);
  assert.deepEqual(NATIVE_UI_REQUIRED_CAPABILITIES, [
    'native_ui.surface',
    'native_ui.design_space_coordinates',
    'native_ui.semantic_layout',
  ]);
  assert.equal(
    NATIVE_UI_FALLBACK_POLICY,
    'NEI frame/background PNG fallback is retired; missing hand-written UI mappings fail closed',
  );
  assert.doesNotMatch(catalogSource, /native_ui\.background_asset/);
  assert.doesNotMatch(catalogSource, /missing required native UI capture is a validation error/);
});

test('capability validator rejects empty, extra, reordered, and policy-drifted schema fields', () => {
  const validAbi = {
    compilerCapabilityAbi: {
      name: capabilityArtifact.name,
      version: capabilityArtifact.version,
      commands: capabilityArtifact.commands,
      requiredCommands: capabilityArtifact.requiredCommands,
      compileScopes: capabilityArtifact.compileScopes,
      nativeUi: capabilityArtifact.nativeUi,
      policy: capabilityArtifact.policy,
    },
    exportAbi: { nativeUi: capabilityArtifact.nativeUi },
    policy: capabilityArtifact.policy,
  };
  assert.deepEqual(validateElysiumCompilerCapabilityAbi(validAbi), []);

  for (const mutate of [
    (abi) => { delete abi.compilerCapabilityAbi; },
    (abi) => { abi.exportAbi.nativeUi.requiredCapabilities = []; },
    (abi) => { abi.exportAbi.nativeUi.requiredCapabilities.push('native_ui.background_asset'); },
    (abi) => { abi.compilerCapabilityAbi.nativeUi.fallbackPolicy = 'legacy fallback allowed'; },
    (abi) => { abi.compilerCapabilityAbi.compileScopes.reverse(); },
    (abi) => { abi.policy.legacyFallback = 'allowed'; },
  ]) {
    const drifted = structuredClone(validAbi);
    mutate(drifted);
    assert.notEqual(validateElysiumCompilerCapabilityAbi(drifted).length, 0);
  }
});

test('compiler client exposes the generated typed native UI capability catalog and gate', () => {
  assert.match(catalogSource, /export const NATIVE_UI_REQUIRED_CAPABILITIES/);
  assert.match(catalogSource, /export const NATIVE_UI_REQUIRED_FILES/);
  assert.match(catalogSource, /export const NATIVE_UI_COORDINATE_SPACE = "nei_pixels"/);
  assert.match(catalogSource, /export const NATIVE_UI_RUNTIME_TRANSFORM = "uniform-scale-to-fit-only"/);
  assert.match(catalogSource, /export type ElysiumCompilerScope = typeof ELYSIUM_COMPILER_COMPILE_SCOPES\[number\]/);
  assert.match(catalogSource, /export const ELYSIUM_COMPILER_CAPABILITY_ABI/);
  assert.match(gateSource, /from '.\/elysium-compiler-capability-abi'/);
  for (const capability of [
    'native_ui.surface',
    'native_ui.design_space_coordinates',
    'native_ui.semantic_layout',
  ]) {
    assert.match(catalogSource, new RegExp(capability.replaceAll('.', '\\.')));
  }
  assert.match(gateSource, /export type ElysiumNativeUiAbi/);
  assert.match(gateSource, /export type ElysiumCompilerCapabilityContract/);
  assert.match(gateSource, /export function assertCompilerNativeUiCapabilityGate/);
  assert.match(gateSource, /'native UI capabilities'/);
  assert.match(gateSource, /'native UI files'/);
  assert.match(gateSource, /abi\.exportAbi\.nativeUi\.coordinateSpace/);
  assert.doesNotMatch(gateSource, /Object\.freeze\(\s*\[/);
});

test('compiler client requires the external compiler command surface', () => {
  assert.match(catalogSource, /export const REQUIRED_COMPILER_COMMANDS/);
  assert.match(scriptCatalogSource, /export const REQUIRED_COMPILER_COMMAND_INVOCATIONS/);
  assert.match(scriptCatalogSource, /export const ELYSIUM_COMPILER_CAPABILITY_ABI/);
  for (const command of ['schemas', 'validate', 'compile']) {
    assert.equal(catalogSource.includes(`"${command}"`), true);
    assert.deepEqual(REQUIRED_COMPILER_COMMAND_INVOCATIONS[command], [command, '--help']);
  }
  assert.match(ensureSource, /function verifyCommandSurface/);
  assert.match(ensureSource, /REQUIRED_COMPILER_COMMAND_INVOCATIONS/);
  assert.match(ensureSource, /validateElysiumCompilerCapabilityAbi\(catalog\.abi\)/);
  assert.match(ensureSource, /ELYSIUM_COMPILER_CAPABILITY_SOURCE\.schemaHash/);
  assert.match(ensureSource, /commands: selectedCommands/);
  assert.match(gateSource, /'compiler commands'/);
  assert.match(gateSource, /commands: string\[\]/);
});

test('compiler handshake attaches validated capabilities before callers can use it', () => {
  assert.match(clientSource, /assertCompilerNativeUiCapabilityGate\(report as ElysiumCompilerHandshake\)/);
  assert.match(clientSource, /capabilities: ElysiumCompilerCapabilityContract/);
  assert.match(clientSource, /return \{ \.\.\.report, capabilities \}/);
  assert.match(clientSource, /commands: capabilities\.commands/);
  assert.match(clientSource, /nativeUiCapabilities: capabilities\.nativeUi\.requiredCapabilities/);
  assert.doesNotMatch(clientSource, /return report;/);
});

test('acceleration compiler boundary reporter consumes the typed native UI capability contract', () => {
  assert.match(reporterSource, /handshake\.capabilities\.nativeUi\.requiredCapabilities/);
  assert.match(reporterSource, /handshake\.capabilities\.nativeUi\.coordinateSpace/);
  assert.match(reporterSource, /handshake\.capabilities\.nativeUi\.runtimeTransform/);
  assert.match(runtimeSource, /verifyAccelerationCompilerBoundary\(\)/);
  assert.doesNotMatch(runtimeSource, /compilerHandshake\.capabilities\.nativeUi/);
  assert.doesNotMatch(runtimeSource, /abi\?\.exportAbi\?\.nativeUi/);
});
