import { test, expect } from '@playwright/test';

for (const offline of [false, true]) test(`${offline ? 'offline' : 'online'} optimize homepage searches and opens recipes`, async ({ page, context, request }) => {
  const manifest = await (await request.get('/api/catalog')).json();
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  if (offline) {
    await page.goto('/offline');
    await page.getByRole('button', { name: '保存完整资料', exact: true }).click();
    await expect(page.getByRole('link', { name: '离线打开', exact: true })).toBeVisible({ timeout: 20000 });
    await context.setOffline(true);
  }
  await page.goto(`/?catalog=${manifest.id}${offline ? '&offline=1' : ''}`);
  await expect(page.locator('.items-column')).toBeVisible();
  await page.locator('.chrome-search-input').fill('shitou');
  await expect(page.locator('.native-browser-surface__fallback-item')).toHaveCount(1);
  const stone = page.getByRole('button', { name: /Stone 石头/ }).first();
  await expect(stone).toBeVisible();
  await expect.poll(() => stone.locator('canvas').evaluate((canvas: HTMLCanvasElement) =>
    canvas.getContext('2d')!.getImageData(0, 0, canvas.width, canvas.height).data.some((v, i) => i % 4 === 3 && v > 0))).toBe(true);
  await stone.click({ button: 'right' });
  await expect(page.locator('.recipe-preview-panel')).toBeVisible();
  await expect(page.locator('.recipe-preview-panel')).not.toContainText('正在加载配方');
  await expect(page.locator('.recipe-preview-panel')).not.toContainText('读取配方失败');
  await page.getByRole('option', { name: /Fixture machine/ }).click();
  await expect(page.locator('.recipe-preview-panel .recipe-view')).toBeVisible();
  await expect(page.locator('.recipe-preview-panel [role="alert"]')).toHaveCount(0);
  const animations = page.getByRole('img', { name: '配方进度动画', exact: true });
  await expect(animations).toHaveCount(2);
  const frames = new Set<string>();
  await expect.poll(async () => {
    frames.add(await animations.first().evaluate((canvas: HTMLCanvasElement) => {
      const ctx = canvas.getContext('2d')!;
      return [[.25,.25],[.75,.25],[.25,.75],[.75,.75]].map(([x,y]) => ctx.getImageData(Math.floor(x!*canvas.width),Math.floor(y!*canvas.height),1,1).data[3]! > 0 ? '1' : '0').join('');
    }));
    return frames.size;
  }, { intervals: [40], timeout: 5000 }).toBe(4);
  await page.getByText('用量与条件', { exact: true }).click();
  await expect(page.locator('.recipe-preview-panel')).toContainText('9,007,199,254,740,993');
  const input = page.locator('.recipe-preview-panel .recipe-view .stack-slot').first();
  await input.getByRole('button', { name: '查看 3 个候选输入', exact: true }).click();
  const choices = page.locator('.choices-dialog');
  await expect(choices.locator('.choice-note').nth(2)).toContainText('排除 1 条前序匹配：Priority reference 前序匹配（精确匹配）');
  await expect(choices.locator('.choice-note').nth(1)).toHaveText('消耗 · 仅忽略字段：frypanKill；其余 NBT 精确匹配');
  await choices.locator('.choice-list .item-link').nth(1).click();
  await expect(input.locator('.quantity')).toHaveText('7');
  await expect(input.locator(':scope > .item-link')).toHaveAttribute('title', /仅忽略字段：frypanKill；其余 NBT 精确匹配/);
  await page.getByRole('option', { name: /Harmony 鸿蒙之眼/ }).click();
  const process = page.locator('.recipe-preview-panel');
  await expect(process.locator('.item-link[title*="共享成功次数"]').first()).toBeVisible();
  await expect(process.locator('.item-link[title*="耗尽对应内部流体存量"]').first()).toBeVisible();
  await expect(process.locator('.item-link[title*="单次模式含历史保底状态"]').first()).toBeVisible();
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process.locator('.item-link[title*="星界阵列决定并行数"]').first()).toBeVisible();
  await expect(process.locator('.item-link[title*="失败次数"]').first()).toBeVisible();
  await page.locator('.chrome-search-input').fill('Runic armor');
  const armor = page.getByRole('button', { name: /^Runic armor 符文护甲/ }).first();
  await armor.click({ button: 'right' });
  await expect(process.locator('.magic-cost-note')).toContainText('展示样本屏障值 3');
  await expect(process).toContainText('样本不稳定性：6');
  await expect(process).toContainText('4座*');
  await expect(process).toContainText('127 后回绕至 −128');
  await page.locator('.chrome-search-input').fill('Filled map');
  await page.getByRole('button', { name: /^Filled map 已填充地图/ }).first().click({ button: 'right' });
  await expect(process).toContainText('周围放置 8 张纸');
  await expect(process).toContainText('待完成地图样本');
  await expect(process).toContainText('由世界分配新地图 ID');
  await expect(process).toContainText('不复制旧探索像素');
  await page.locator('.chrome-search-input').fill('Inscriber input');
  await page.getByRole('button', { name: /^Inscriber input 压印材料/ }).first().click({ button: 'right' });
  await expect(process).toContainText('压印：保留模板');
  await expect(process).toContainText('会优先执行命名');
  await expect(process.locator('.stack-slot > .item-link[title*="AE2 精确匹配"]').first()).toBeVisible();
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('合成：清空两个模板槽');
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('注册的下模板不构成材料要求');
  await page.locator('.chrome-search-input').fill('Enchanter material');
  await page.getByRole('button', { name: /^Enchanter material 附魔材料/ }).first().click({ button: 'right' });
  await expect(process).toContainText('附魔等级 1：材料槽须放入至少 3 件、少于 6 件');
  await expect(process).toContainText('需要 9 级经验');
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('附魔等级 2：材料槽须放入至少 6 件、少于 9 件');
  await expect(process).toContainText('需要 15 级经验');
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('附魔等级 5：材料槽须放入至少 15 件');
  await expect(process).not.toContainText('少于 18 件');
  await page.locator('.chrome-search-input').fill('Vat reagent');
  await page.getByRole('button', { name: /^Vat reagent 储液罐反应物/ }).first().click({ button: 'right' });
  await expect(process).toContainText('基础能量 1200 RF');
  const vatInput = process.locator('.stack-slot').first();
  await expect(vatInput.locator(':scope > .item-link')).toContainText('≤3');
  await vatInput.getByRole('button', { name: '查看 2 个候选输入', exact: true }).click();
  await expect(choices.locator('.choice-list .item-link').first()).toContainText('≤3');
  await choices.locator('.choice-list .item-link').nth(1).click();
  await expect(vatInput.locator(':scope > .item-link')).not.toContainText('≤');
  await expect(vatInput.locator(':scope > .item-link')).toHaveAttribute('title', /不消耗/);
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('第二物品槽可以空置');
  await process.getByText('额外槽消耗规则', { exact: true }).click();
  await expect(process).toContainText('Vat optional 额外材料');
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('产量为零');
  await expect(process).toContainText('不计为可获取产物');
  await page.locator('.chrome-search-input').fill('Alloy input');
  await page.getByRole('button', { name: /^Alloy input 合金材料/ }).first().click({ button: 'right' });
  await expect(process).toContainText('同一叠不会拆给多个需求');
  await expect(process).toContainText('第 2 槽、第 1 槽');
  await expect(process).toContainText('所有产物共享一次随机抽取');
  await expect(process.locator('.stack-slot > .item-link[title*="本项阈值 0.0"]')).toContainText('0–3');
  await expect(process.locator('.stack-slot > .item-link[title*="本项阈值 0.0"]')).toHaveAttribute('title', /1\/16,777,216/);
  await page.locator('.chrome-search-input').fill('Splice input');
  await page.getByRole('button', { name: /^Splice input 装配材料/ }).first().click({ button: 'right' });
  await expect(process).toContainText('六个材料槽');
  await expect(process).toContainText('第 6 槽、第 1 槽');
  await expect(process).toContainText('不保证每次掉一点耐久');
  await expect(process.locator('.stack-slot > .item-link[title*="完工时尝试损耗工具"]')).toHaveCount(2);
  await page.locator('.chrome-search-input').fill('SAG input');
  await page.getByRole('button', { name: /^SAG input 磨粉材料/ }).first().click({ button: 'right' });
  await expect(process).toContainText('研磨珠库存槽可留空');
  await expect(process.locator('.stack-slot > .item-link[title*="可选研磨珠库存"]')).toContainText('可选');
  await expect(process.locator('.stack-slot > .item-link[title*="本项阈值 0.5"]')).toContainText('2×次数');
  await process.getByText('研磨珠参数（依次匹配）', { exact: true }).click();
  await expect(process).toContainText('产量 ×2.5');
  await expect(process).toContainText('能耗 ×0.5');
  await page.locator('.chrome-search-input').fill('Soul bound product');
  await page.getByRole('button', { name: /^Soul bound product 灵魂绑定产物/ }).first().click();
  await expect(process).toContainText('启动需要 272 XP');
  await expect(process).toContainText('仍检查经验门槛');
  await expect(process).toContainText('空瓶和产物均不产出');
  await page.locator('.chrome-search-input').fill('Broken spawner');
  await page.getByRole('button', { name: /^Broken spawner 破损刷怪笼/ }).first().click({button:'right'});
  await expect(process).toContainText('未列出的生物也可能匹配');
  await expect(process).toContainText('Zombie bound spawner');
  await process.getByRole('button',{name:'查看 2 个候选输入',exact:true}).click();
  await choices.locator('.choice-list .item-link').nth(1).click();
  await expect(process).toContainText('Sheep bound spawner');
  await page.locator('.chrome-search-input').fill('shitou');
  await page.getByRole('button', { name: /Stone 石头/ }).first().click({ button: 'right' });
  await page.getByRole('option', { name: /Rolling machine 轧制机/ }).click();
  await expect(process).toContainText('每次从每个有物品的格子消耗一件，不返还容器');
  await expect(process).toContainText('保留最后一份');
  await expect(process).toContainText('每次推进消耗 50 RF');
  await process.getByRole('button', { name: '下一页', exact: true }).click();
  await expect(process).toContainText('当前配置关闭机器耗能');
  await page.getByRole('option', { name: /BuildCraft Assembly 激光装配台/ }).click();
  await expect(process).toContainText('激光能量 700 RF');
  await expect(process).toContainText('不同候选可以混合凑足同一份需求');
  await expect(process).toContainText('不回溯重分配');
  const assemblyInput=process.locator('.stack-slot').first();
  await expect(assemblyInput.locator(':scope > .item-link')).toHaveAttribute('title', /BuildCraft.*缺失与空标签不同/);
  await assemblyInput.getByRole('button', { name: '查看 2 个候选输入', exact: true }).click();
  await expect(page.locator('.choices-dialog .choice-note').nth(1)).toContainText('源模板通配，忽略变体与 NBT');
  await page.locator('.choices-dialog .choice-list .item-link').nth(1).click();
  await page.locator('.chrome-search-input').fill('Empty robot');
  await page.getByRole('button', { name: /^Empty robot 空机器人/ }).first().click({ button: 'right' });
  await expect(process).toContainText('每 16 游戏刻检查配方与输出空间');
  const integration = process.locator('.recipe-flow .stack-slot');
  const result = integration.nth(3).locator(':scope > .item-link');
  await expect(result).toHaveAttribute('title', /Initialized red robot/);
  await expect(integration.nth(2).locator(':scope > .item-link')).toHaveCount(0);
  await integration.nth(1).getByRole('button', { name: '查看 2 个候选输入', exact: true }).click();
  await choices.locator('.choice-list .item-link').nth(1).click();
  await expect(result).toHaveAttribute('title', /Initialized blue robot/);
  await integration.nth(0).getByRole('button', { name: '查看 2 个候选输入', exact: true }).click();
  await choices.locator('.choice-list .item-link').nth(1).click();
  await expect(result).toHaveAttribute('title', /Charged blue robot/);
  await integration.nth(2).getByRole('button', { name: '查看 1 个候选输入', exact: true }).click();
  await choices.locator('.choice-list .item-link').first().click();
  await expect(integration.nth(1).locator(':scope > .item-link')).toHaveCount(0);
  await expect(integration.nth(2).locator(':scope > .item-link')).toHaveAttribute('title', /Blue robot board/);
  await expect(result).toHaveAttribute('title', /Charged blue robot/);
  await page.locator('.chrome-search-input').fill('water');
  await page.getByRole('button', { name: /^Water/ }).first().click({ button: 'right' });
  await page.getByRole('option', { name: /BuildCraft Refinery 精炼厂/ }).click();
  await expect(process).toContainText('每次尝试的能量为 30 RF');
  await expect(process).toContainText('部分流体已扣除而没有产物');
  await process.getByText('进液许可与前序配方', { exact: true }).click();
  await expect(process).toContainText('helium');
  await expect(process).toContainText('hydrogen');
  await page.locator('.chrome-search-input').fill('shitou');
  await page.getByRole('button', { name: /Stone 石头/ }).first().click({ button: 'right' });
  await page.getByRole('option', { name: /IC2 Blast Furnace 高炉/ }).click();
  await expect(process).toContainText('当前热量门槛为 50000');
  await expect(process).toContainText('完工时只消耗一件主材料');
  await expect(process).toContainText('换料不会清零进度');
  await expect(process).toContainText('副产物可能部分或全部丢失');
  await expect(process.locator('.stack-slot').nth(1).locator(':scope > .item-link')).toHaveAttribute('title', /阶段.*空 NBT/);
  await page.screenshot({ path: `test-results/pilot-${offline ? 'offline' : 'online'}.png`, fullPage: true });
  expect(errors).toEqual([]);
});

test('production offline library saves the shell and verified images', async ({ page, context, request }) => {
  const manifest = await (await request.get('/api/catalog')).json();
  const image = manifest.files.find((file: { kind: string }) => file.kind === 'image');
  await page.goto('/offline');
  await page.getByRole('button', { name: '保存完整资料', exact: true }).click();
  await expect(page.getByRole('link', { name: '离线打开', exact: true })).toBeVisible({ timeout: 20000 });
  await context.setOffline(true);
  await page.reload();
  await expect(page.getByRole('link', { name: '离线打开', exact: true })).toBeVisible();
  const digest = await page.evaluate(async (url: string) => {
    const response = await fetch(url);
    if (!response.ok) throw new Error('Offline image failed: ' + response.status);
    return [...new Uint8Array(await crypto.subtle.digest('SHA-256', await response.arrayBuffer()))].map(n => n.toString(16).padStart(2, '0')).join('');
  }, `/assets/${manifest.id}/${image.path}`);
  expect(digest).toBe(image.sha256);
  await page.evaluate(async ({ id, path }) => {
    const db = await new Promise<IDBDatabase>(resolve => { const open = indexedDB.open('neonei.catalog'); open.onsuccess = () => resolve(open.result); });
    await new Promise<void>((resolve, reject) => { const tx = db.transaction('files', 'readwrite'); tx.oncomplete = () => resolve(); tx.onerror = () => reject(tx.error); tx.objectStore('files').put({ catalog: id, path, body: new Uint8Array([0]).buffer }); });
    db.close();
  }, { id: manifest.id, path: image.path });
  expect(await page.evaluate(async url => (await fetch(url)).status, `/assets/${manifest.id}/${image.path}`)).toBe(503);
});
