export const ASPECT_HASH_TO_NAME: Record<string, string> = {
  '-fRy34lCPpilc8Z_sZSJ_A==': 'Custom5',
  '-nKmPi5gMCSOtUhFvr9bmQ==': 'Terra',
  '-WZow0DtPpGnHLV45_DGeQ==': 'Machina',
  '1-7eh6qDP-OaujRqJfbFhg==': 'Vacuos',
  '1m-dABluMX2uBT_FhScEAg==': 'Infernus',
  '1R-2txyrPJmXA6XkPrvt1w==': 'Vinculum',
  '4xKBfaTGMJeUx49ayvYeAQ==': 'Iter',
  '5DVPto4sMru9OuQt5wSOyQ==': 'Tempus',
  '5DyTRPs8MJ6PYX4G0eRZqw==': 'Strontio',
  '6tN9HgR2Pf-iJ_KPD-XjZw==': 'Auram',
  '6vCtvcj5P5SqrhJ0yJ_2rw==': 'Mortuus',
  '6wyGiXkuM9GsneM2VLTZnA==': 'Cognitio',
  '8EsH2RaJPrKrDtxtBaDAHw==': 'Lux',
  'afM_KWYzPDmY5GO8JROG4g==': 'Praecantatio',
  'AksLhS6LMPm8ybiVt8FOQg==': 'Caelum',
  'aoygy2N2Nja277OSV7JRwQ==': 'Fabrico',
  'BCSsmpzMN46WiD5XG9MMow==': 'Sensus',
  'BtMtkzYEPK-mSyce4dQWdA==': 'Corpus',
  'C50BANQcPpyh6b5ZrtJRzg==': 'Electrum',
  'D3Aoy7N3OEGbK51rIZ0eqQ==': 'Gelum',
  'Dn_GtxS4OJG4_gPw2oHb9Q==': 'Sano',
  'E-fKHZn8PFGDOccGLNcGlQ==': 'Motus',
  'fAEKF3UUPgWZnEuxrVzERA==': 'Aer',
  'ggXIdIc2MF-Q6GX1ZFbmZQ==': 'Vitium',
  'HCGuZvZZN2uRU9nfPMn0KQ==': 'Radio',
  'HmIkkQgLO9G_-BPPnioU-g==': 'Custom4',
  'httSNrPKMtyhMClS5CI0hA==': 'Terminus',
  'jrBYqg9GNC67fgH4YO1Ciw==': 'Permutatio',
  'JSVWkWxqNvSvkUm-PvuYrQ==': 'Ignis',
  'k7P4LDyCMwOOlzWi06MCOw==': 'Bestia',
  'KhtAvW0yPHy54jAIHjPecQ==': 'Aer',
  'L-H5p000MF6BDWDwXnIxMA==': 'Humanus',
  'l1RE8amgNwmfR8ghqw7H7Q==': 'Metallum',
  'L6Zm8UJCPR-kN8Pyc-rpRQ==': 'Fames',
  'lb6OgOxrMDST09phum6CDQ==': 'Aqua',
  'ldfQSXiFOV6pd_1_EJOAgQ==': 'Instrumentum',
  'Lk6wUrkjPjCe-YqOxfsl8w==': 'Volatus',
  'MuB2lsJuNdmCF4lhqwcbrg==': 'Venenum',
  'Na3q2u0lNYWL36IAyx7FsQ==': 'Ordo',
  'nEjO6v9lPa-VJWzGjJeW-g==': 'Tabernus',
  'nKbQ0Sa2NhedmdZ6Vnnmsg==': 'Herba',
  'NuRAe6LIMcyuW4RDj63sRA==': 'Perfodio',
  'P7pQ6Lf8P7GUv5XBLFQiWQ==': 'Potentia',
  'Poumcd6dObyMFklMmRZhCA==': 'Desidia',
  'Q4nRW5lBNBWlzyGj2otx4A==': 'Superbia',
  'QDaA6TmDNCevYfB1_1X5_g==': 'Arbor',
  'qhqWI6NINGi4YWMWtHSYfw==': 'Spiritus',
  'QTNcwPhBNKCU_xKlq6Y_kA==': 'Telum',
  'qXBLKgqdPUaHvCjH-kYluA==': 'Custom3',
  'ra0yIkxNMrePWO5SXchRzA==': 'Exanimis',
  'RhT0hi7oORaI1LfXp1nYrg==': 'Pannus',
  'rK3PeeWdPXaqfe0NPJjSWg==': 'Nebrisum',
  'RnKdNXSwNY-iF03t_6-hVA==': 'Alienis',
  's6V8MqcaPGax8vgKFH5wIw==': 'Luxuria',
  't8exCO8yOae9HRCzrI36jQ==': 'Vitreus',
  'tHfwXp_iOUy1TihQGhvXpw==': 'Limus',
  'U0kPtlGGOm-fSAQYNW0zOw==': 'Tenebrae',
  'U9L_Rta5NaW5FrcPOUZD3g==': 'Victus',
  'vmSiwpQGOyih-5J8QGrxyg==': 'Messis',
  'VSal_9xpNbOmJsmoVLzE3w==': 'Magneto',
  'WWH64YZjMzau-0OkV6zNjg==': 'Perditio',
  'x_Sm1fPpOsaibfaWr6X2dA==': 'Tempestas',
  'X0VrwVqpNMKt2E32zEZXHA==': 'Custom2',
  'XLChheNtPDOdHO9K1DlOtw==': 'Custom1',
  'ygCZCVUhNvOsUg1MyAAorw==': 'Invidia',
  'YNC_PFRwN3-xtzjumexY-A==': 'Meto',
  'YQCLwqbQOsyWc7-EbyaqiQ==': 'Gula',
  'ZCUXhgvfNBG3PL8lH9zmNA==': 'Ira',
  'zH-kGDdhOi61DIROt1fupg==': 'Tutamen',
  'ziktSttgODmt120cOv1Kcg==': 'Lucrum',
};

export const ASPECT_COLORS: Record<string, string> = {
  Aer: '#f7fbff',
  Terra: '#7c4b1f',
  Ignis: '#ff6b2c',
  Aqua: '#4cd6ff',
  Ordo: '#f1d97a',
  Perditio: '#4e4e56',
  Vacuos: '#202080',
  Praecantatio: '#be7dff',
  Potentia: '#ffab57',
  Lux: '#ffe26f',
  Motus: '#d2ce84',
  Victus: '#f65d63',
  Bestia: '#deb887',
  Herba: '#76d56d',
  Sano: '#8de89b',
  Gelum: '#9fdfff',
  Tempestas: '#66cfd8',
  Venenum: '#7ee25f',
  Auram: '#ffe26f',
  Volatus: '#cad6db',
  Instrumentum: '#7a848d',
  Metallum: '#b7bcc2',
  Vinculum: '#ff79c8',
  Cognitio: '#d8a7db',
  Sensus: '#ff8094',
  Permutatio: '#97cc65',
  Praemunio: '#69c0b5',
  Exanimis: '#9486c9',
  Gravitas: '#6f6f6f',
  Iter: '#ffb06b',
  Alienis: '#b57bd9',
  Vitium: '#8b0000',
  Aversio: '#cf4d5f',
  Desiderium: '#ff5fbe',
  Limus: '#9fba66',
  Messis: '#daa56a',
  Metumbo: '#b48658',
  Tutamen: '#b7b070',
  Lucrum: '#f0d16c',
  Corpus: '#cd853f',
  Humanus: '#ffb6c1',
  Mortuus: '#8d7e96',
  Fames: '#8b5e34',
  Desidia: '#7f8a95',
  Caelum: '#87cefa',
};

export const ASPECT_ICON_DAMAGE: Record<string, number> = {
  Aer: 1,
  Terra: 2,
  Ignis: 3,
  Aqua: 4,
  Ordo: 5,
  Perditio: 6,
  Vacuos: 7,
  Praecantatio: 8,
  Potentia: 9,
  Lux: 10,
  Motus: 11,
  Victus: 12,
  Bestia: 13,
  Herba: 14,
  Sano: 15,
  Tempestas: 16,
  Vitreus: 17,
  Spiritus: 18,
  Mortuus: 19,
  Instrumentum: 21,
  Metallum: 22,
  Vinculum: 23,
  Cognitio: 24,
  Sensus: 25,
  Permutatio: 26,
  Praemunio: 27,
  Exanimis: 28,
  Gravitas: 29,
  Venenum: 30,
  Iter: 31,
  Auram: 32,
  Alienis: 33,
  Vitium: 34,
  Aversio: 35,
  Desiderium: 36,
  Gelum: 37,
  Limus: 38,
  Messis: 39,
  Metumbo: 40,
  Tutamen: 41,
  Lucrum: 42,
  Volatus: 43,
  Corpus: 44,
  Humanus: 45,
};

const ASPECT_NAME_MAP: Record<string, string> = {
  aer: 'Aer',
  terra: 'Terra',
  ignis: 'Ignis',
  aqua: 'Aqua',
  ordo: 'Ordo',
  perditio: 'Perditio',
  vacuos: 'Vacuos',
  praecantatio: 'Praecantatio',
  potentia: 'Potentia',
  lux: 'Lux',
  motus: 'Motus',
  victus: 'Victus',
  bestia: 'Bestia',
  herba: 'Herba',
  sano: 'Sano',
  venenum: 'Venenum',
  mortuus: 'Mortuus',
  iter: 'Iter',
  auram: 'Auram',
  cognitio: 'Cognitio',
  sensus: 'Sensus',
  corpus: 'Corpus',
  humanus: 'Humanus',
  volatus: 'Volatus',
  fames: 'Fames',
  desidia: 'Desidia',
  caelum: 'Caelum',
  spiritus: 'Spiritus',
  vitreus: 'Vitreus',
  metallum: 'Metallum',
  permutatio: 'Permutatio',
  exanimis: 'Exanimis',
  alienis: 'Alienis',
  vitium: 'Vitium',
  limus: 'Limus',
  messis: 'Messis',
  tutamen: 'Tutamen',
  lucrum: 'Lucrum',
  tempestas: 'Tempestas',
  tenebrae: 'Tenebrae',
  vinculum: 'Vinculum',
  instrumentum: 'Instrumentum',
  infernus: 'Infernus',
  tempus: 'Tempus',
  strontio: 'Strontio',
  fabrico: 'Fabrico',
  electrum: 'Electrum',
  radio: 'Radio',
  terminus: 'Terminus',
  tabernus: 'Tabernus',
  telum: 'Telum',
  pannus: 'Pannus',
  nebrisum: 'Nebrisum',
  luxuria: 'Luxuria',
  magneto: 'Magneto',
  invidia: 'Invidia',
  meto: 'Meto',
  gula: 'Gula',
  ira: 'Ira',
  arbor: 'Arbor',
  custom1: 'Custom1',
  custom2: 'Custom2',
  custom3: 'Custom3',
  custom4: 'Custom4',
  custom5: 'Custom5',
  '未知源质': 'Unknown',
  '未知要素': 'Unknown',
  unknown: 'Unknown',
};

export function normalizeAspectName(name: string): string {
  const trimmed = name.trim();
  if (!trimmed) return 'Unknown';

  const lowered = trimmed.toLowerCase();
  const mapped = ASPECT_NAME_MAP[lowered] || ASPECT_NAME_MAP[trimmed];
  if (mapped) return mapped;

  // For raw aspect keys not yet in the dictionary, prefer readable title-case over Unknown.
  if (/^[a-z][a-z0-9_]*$/i.test(trimmed)) {
    return trimmed.charAt(0).toUpperCase() + trimmed.slice(1);
  }

  return trimmed;
}

export function parseAspectNameFromLocalized(localizedName?: string): string | null {
  if (!localizedName) return null;

  const zh = localizedName.match(/要素:\s*(.+)$/);
  if (zh) {
    return normalizeAspectName(zh[1]);
  }

  const en = localizedName.match(/aspects?:\s*(.+)$/i);
  if (en) {
    return normalizeAspectName(en[1]);
  }

  return null;
}
